#ifndef __DEFINES_H__
#define __DEFINES_H__
#define WRITEBYTE(WORD,BYTESTARTPOS,BYTE) (WORD = (WORD&~(0xFF<<BYTESTARTPOS))|(BYTE<<BYTESTARTPOS))
#define READBYTE(WORD,BYTESTARTPOS) ((WORD>>BYTESTARTPOS)&0xFF)
#define WRITENIBBLE(WORD,NIBBLESTARTPOS,NIBBLE) (WORD = (WORD&~(0xF<<NIBBLESTARTPOS))|(NIBBLE<<NIBBLESTARTPOS))
#define READNIBBLE(WORD,NIBBLESTARTPOS) ((WORD>>NIBBLESTARTPOS)&0xF)
#define WRITEBIT(WORD,BITSTARTPOS,BIT) (WORD = (WORD&~(1<<BITSTARTPOS))|(BIT<<BITSTARTPOS))
#define READBIT(WORD,BITSTARTPOS) ((WORD>>BITSTARTPOS)&1)
#endif